version: '3.9'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./google_key.json:/app/google_key.json:ro
    restart: unless-stopped
